### ISSUE TITLE
Team Project Button not at center

### ISSUE THREAD

**Issue by Gorgeous-Patrick** [samrobbins85/hugo-developer-portfolio#19]
![image](https://user-images.githubusercontent.com/33488623/205425749-bc9ba095-8900-49f1-aefb-b7c76c3449eb.png)

As is shown in the picture, the TEAM PROJECT button is not aligned. 

The bug is triggered when there is no github link.

**Comment by samrobbins85** [comment]
Thanks for reporting, this should now be resolved
