### ISSUE TITLE
No skills section and duplicate certifications section

### ISSUE THREAD

**Issue by albero94** [samrobbins85/hugo-developer-portfolio#2]
Hi Sam! I was taking a look at your portfolio theme and looks amazing!

I tried to use it myself and realize that no matter what I did with the skills section in homepage.yml nothing would appear in the website.

I went to index.html and saw that there is no section for skills, I also notieced certifications is duplicated. I'm not sure if you would like to take a look at this.

Best,
Alvaro.

**Comment by samrobbins85** [comment]
Hi, yeah I forgot to update the example site because I've removed the skills section. I'll get on that tomorrow. Didn't realise I duplicated the certifications section but I'll have a look at it too. Thanks very much for your feedback

**Comment by samrobbins85** [comment]
That should be all fixed now, let me know how you get on

**Comment by albero94** [comment]
Thanks for the effort!
