### ISSUE TITLE
Leadership & Teamwork section always shows up in About

### ISSUE THREAD

**Issue by sebescudie** [samrobbins85/hugo-developer-portfolio#3]
Hey there,

I noticed the _Leadership & Teamwork_ section is always present in the About page, even if you specify 

```
leadership:
  enable: false
```
in `about.yml`. 

I solved it locally by putting the whole `Experience` section inside the `{{ range .Site.Data.about.leadership.item }}` block in `layouts/about/list.html`, not sure this is the right way to do though!

Thanks for this theme.

**Comment by samrobbins85** [comment]
Hi! Thanks for this issue, I totally missed this one. The "best" solution (at least to me) is by wrapping it in `{{ if .Site.Data.about.leadership.enable }}`. I've updated the theme with this, you can see it in commit 128b743.

**Comment by sebescudie** [comment]
Thanks for the prompt fix!

First time ever I'm using Hugo so I'm sure you're right :)

**Comment by samrobbins85** [comment]
No worries, let me know if you see any other issues or need any help
