### ISSUE TITLE
Homepage is not loading up properly

### ISSUE THREAD

**Issue by shapan1** [samrobbins85/hugo-developer-portfolio#6]
Following the [quickstart guide](https://gohugo.io/getting-started/quick-start/), I got your theme and ran it with all the default settings and it doesn't load up the page properly as shown in image below.
![image](https://user-images.githubusercontent.com/16653640/93288490-eb73f400-f7a9-11ea-8259-8bd7dbfd71b8.png)

**Comment by samrobbins85** [comment]
As referenced in the [README](https://github.com/samrobbins85/hugo-developer-portfolio#configuration), this site requires configuration in order to work correctly. It's likely that you have a range of errors in your console about missing files
