### ISSUE TITLE
Image not displayed for blog posts

### ISSUE THREAD

**Issue by varac** [samrobbins85/hugo-developer-portfolio#7]
First of all, thanks for your nice theme!

I noticed that the [image in the front matter of a blog post](https://github.com/samrobbins85/hugo-developer-portfolio#blogs) is not displayed (not even at the [hugo-developer-portfolio demo page](https://themes.gohugo.io//theme/hugo-developer-portfolio/blog).
Was it never supposed to be there or taken out and forgotten to remove the front matter element in the docs ?

**Comment by samrobbins85** [comment]
Thanks very much! Removed those references now
