### ISSUE TITLE
Error in loading CSS

### ISSUE THREAD

**Issue by HariprasadManimozhi** [samrobbins85/hugo-developer-portfolio#9]
I' am able to apply the theme "hugo-developer-portfolio", While applying the theme "tailwind-developer-website", the following error pops up:

Error: Error building site: POSTCSS: failed to transform "css/tailwind.css" (text/css): resource "css/css/tailwind.css_0a7609e807cbb0441390b6ce32d26025" not found in file cache

Can u let know why this error occurs?

**Comment by samrobbins85** [comment]
While it is open source, the tailwind developer theme isn't really set up yet for people to use. The reason you're getting this error is that you need to have the tailwindcss npm package installed on your website and tailwind all set up

**Comment by HariprasadManimozhi** [comment]
> While it is open source, the tailwind developer theme isn't really set up yet for people to use. The reason you're getting this error is that you need to have the tailwindcss npm package installed on your website and tailwind all set up

Thanks.. Can u let know how to setup this one by posting picture of the structure of the project folders/folders

**Comment by samrobbins85** [comment]
It's more than you'd need, but this is my repo that uses this theme https://github.com/samrobbins85/next-portfolio-website
